version: "3"

services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html/
      - ./trust:/var/www/trust
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - '8080:80'
    links:
      - mariadb
  mariadb:
    image: "mariadb"
    restart: 'no'
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - ./docker/mariadb/seed:/docker-entrypoint-initdb.d
      - ./docker/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "formulize"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
