name: e2e test suite

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  e2e-test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Set file/directory permissions
      run: |
        chmod 777 trust uploads modules templates_c cache mainfile.php
    - name: Run Docker Compose up
      run: |
        docker-compose up -d
    - name: Wait for mysql
      uses: smurfpandey/wait-for-it@main
      with:
        host: localhost
        port: 3306
        timeout: 60
    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
        | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
        && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
        | sudo tee /etc/apt/sources.list.d/ngrok.list \
        && sudo apt update \
        && sudo apt install ngrok
    - name: ngrok token association
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Start ngrok
      run: |
        ngrok http 8080
    # - name: Connect to saucelabs
    #   uses: saucelabs/sauce-connect-action@v2
    #   with:
    #     username: ${{ secrets.SAUCE_USERNAME }}
    #     accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
    #     tunnelName: ${{ github.run_id }}
    # - name: Saucectl RUN
    #   uses: saucelabs/saucectl-run-action@v4
    #   with:
    #     sauce-username: ${{ secrets.SAUCE_USERNAME }}
    #     sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
    #     tunnel-name: ${{ github.run_id }}
    # - name: Install dependencies
    #   run: npm ci
    #   working-directory: tests/e2e
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    #   working-directory: tests/e2e
    # - name: Run Playwright tests
    #   run: npx playwright test
    #   working-directory: tests/e2e
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: tests/e2e/test-report/
    #     retention-days: 30
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
