name: e2e test suite

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  e2e-test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Run Docker Compose
      run: |
        docker-compose up -d
    - name: Wait for mysql
      uses: smurfpandey/wait-for-it@main
      with:
        host: localhost
        port: 3306
        timeout: 60
    - name: Install dependencies
      run: npm ci
      working-directory: ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ci
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ci
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
