name: e2e test suite

on: [push]

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}
  SAUCE_TUNNEL_NAME: ${{ github.GITHUB_RUN_ID }}
  GITHUB_REF_NAME: ${{ github.GITHUB_REF_NAME }}
  GITHUB_SHA: ${{ github.GITHUB_SHA }}

jobs:
  e2e-test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Connect to saucelabs
      uses: saucelabs/sauce-connect-action@v2
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
    - name: Run Docker Compose
      run: |
        docker-compose up -d
    - name: Wait for mysql
      uses: smurfpandey/wait-for-it@main
      with:
        host: localhost
        port: 3306
        timeout: 60
    - name: Saucectl RUN
      uses: saucelabs/saucectl-run-action@v4
        # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    # - name: Run e2e tests on selenium
    #   run: |
    #     se-interpreter ci/travis/interpreter_config.json
