name: e2e test suite

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  e2e-test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Connect to saucelabs
      uses: saucelabs/sauce-connect-action@v2
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnelName: ${{ github.GITHUB_RUN_ID }}
    - name: Run Docker Compose
      run: |
        docker-compose up -d
    - name: Wait for mysql
      uses: smurfpandey/wait-for-it@main
      with:
        host: localhost
        port: 3306
        timeout: 60
    - name: Saucectl RUN
      uses: saucelabs/saucectl-run-action@v4
      with:
        sauce-username: ${{ secrets.SAUCE_USERNAME }}
        sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnel-name: ${{ github.GITHUB_RUN_ID }}
