name: e2e test suite

on: [push]

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  e2e-test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Connect to saucelabs
      uses: saucelabs/sauce-connect-action@v2
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnelName: github-action-tunnel
    - name: Run Docker Compose
      run: |
        docker-compose up -d
    - name: Saucectl RUN
      uses: saucelabs/saucectl-run-action@v4
      with:
        working-directory: ci/selenium2-tests
